#!/bin/sh
export LD_LIBRARY_PATH=.:$LD_LIBRARY_PATH
export MALLOC_CHECK_=0

while true; do
	echo Iniciando sphere. CTRL-C para parar o script.
	sleep 2
	./sphere
	echo Sphere terminado. CTRL-C para abortar ou espere para reiniciar.
	sleep 5
done
