#!/bin/bash

if [ -z "$1" ]; then
	BRANCH="master"
else
	BRANCH="$1"
fi

echo "***********" $('date') $BRANCH "*************" >> svnlog.txt
#svn update --username xx --password xx >> svnlog.txt

git fetch
git checkout $BRANCH >> svnlog.txt
git pull >> svnlog.txt

S=`git show | grep  -e commit -e Date`

IFS=$'\n'
for line in $S; do
	case $line in
	commit* )
		COMMIT=${line#* }	#commit 1231231231231231 - get only the number
		COMMIT=${COMMIT:0:6}	#first 6 digits
	;;
	Date* )
		DATE=${line#* }	#Date:   Mon Feb 29 14:30:38 2016 -0300 - get only the date
		break
	;;
	esac	
done;
unset IFS

echo "[FUNCTION upd_repo_info]
VAR.repo_commit=$COMMIT ( <strtrim $DATE> $BRANCH )
[EOF]
" > scripts/myt/version.scp

