#!/bin/bash

echo "***********" $('date') "*************" >> svnlog.txt
#svn update --username xx --password xx >> svnlog.txt
git pull >> svnlog.txt

S=`git show | grep  -e commit -e Date`
COMMIT=${S#* }
COMMIT=${COMMIT:0:6}
DATE=${S#*:}

echo "
[FUNCTION upd_repo_info]
VAR.repo_commit=$COMMIT ( <strtrim $DATE> )
[EOF]
" > scripts/myt/version.scp

